tvkitchen/countertop

package.json, yarn.lock
This adds a bunch of babel packages that somehow got lost in the fray during the great rebase of 2020.
These packages were originally added during the appropriate time, I swear.
1. `yarn lint`
- `yarn install`
Related to #6
=> Add babel packages

.github/ISSUE_TEMPLATE/discussion.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/task.md
This replaces the simple bolded text with `####` (H4) headers, which render in a similar size w/in GitHub but add consistent margin between the header and the following content. (Otherwise, whether the next line of text appeared directly below the header or not would depend on if the contributor entered a newline between them or not, and that’s just sloppy.)
It also adds a much-needed period to one of the descriptions.
For some reason, opening this PR didn't prefill with the PR template. But in any case, it's just a GitHub-specific issue template change with no associated issue.
=> Use Markdown headers for issue template sections

package.json, yarn.lock
Travis is testing on a more recent version of Node.js which requires
updated packages for some reason.  This implements that update.
Issue #39 Node 13.13 broke babel
This PR fixes our universally failing build on travis.
This will be tested by opening a PR and seeing if Travis succeeds
* `yarn install`
Resolves #39
=> Upgrade yarn lockfile

.eslintrc.js, jest.config.js, lib/utils/moduleAlias.js, package.json
We use `module-alias` to let us absolutely import modules from defined roots. However, Jest doesn’t pick up these defined roots automatically; instead, we need to replicate them in our Jest configuration.
This PR adds that configuration. Note that Jest uses regex and suggests you include beginning/end anchors for explicitness, so we do.
1. `yarn test`
None.
Resolves #35
=> Configure Jest to support absolute imports

docs/TESTING.md, jest.config.js, lib/utils/jest.setup.js, package.json
This PR toggles the silence option on the Winston console transport stream when the `NODE_ENV` is `test`. This environment variable is automatically set when running `yarn test`, so this silences the logger. It's one of several competing solutions discussed in [this StackOverflow question](https://stackoverflow.com/questions/38363292/disable-winston-logging-when-running-unit-tests).
Downsides:
1. it intermingles a test-specific flag with the production code instead of doing so in a Jest setup file;
2. it doesn't follow Jest's `--silent` flag on the command line (should it?).
Other StackOverflow solutions address those downsides. Could investigate adding to a Jest setup further if needed. One line PR was tempting.
1. Add `logger.info('whee')` to any test file.
2. Run `yarn test`. You …
=> Silences Winston console output during tests

package.json, src/components/ingestion/HttpIngestionEngine.js, src/components/ingestion/__test__/HttpIngestionEngine.unit.test.js, yarn.lock
Creates a HTTP ingestion engine that can serve as a base for a HDHomeRun engine.
1. `yarn test`
Resolves #73
=> Create HTTP ingestion engine

package.json, src/components/countertop/CountertopCoordinator.js, src/components/countertop/CountertopStation.js, src/components/countertop/CountertopStream.js, src/components/countertop/CountertopTopology.js, src/components/countertop/index.js, src/tests/countertop/__snapshots__/topology.int.test.js.snap, src/tests/countertop/topology.int.test.js, src/tools/utils/__test__/__snapshots__/countertop.unit.test.js.snap, src/tools/utils/__test__/__snapshots__/jest.unit.test.js.snap, src/tools/utils/__test__/countertop.unit.test.js, src/tools/utils/__test__/index.unit.test.js, src/tools/utils/__test__/jest.unit.test.js, src/tools/utils/countertop.js, src/tools/utils/index.js, src/tools/utils/jest.js, yarn.lock
This PR adds the first portion of the countertop, which is the central workspace of the TV kitchen ultimately responsible for setting up the appliances and data streams to process all unique data streams.
Specifically, it adds the countertop components necessary to register appliances and convert a set of registered appliances into a data flow topology (the various data paths between sections of the countertop which will transform that data into new formats).
This begins to implement some of the API described in #82.
Since this is the first countertop PR, it defines a few key classes which will be expanded on in future PRs:
* `CountertopCoordinator` defines the developer API -- developers will be working with this entity directly.  It is where new appliances are registered.  It generates …
=> Create countertop topology generation

src/tools/utils/__test__/countertop.unit.test.js, src/tools/utils/countertop.js
There was 
Issue #95
This PR fixes an issue where generateTributaryMaps would sometimes throw an error if a populated streamOutputMap did not contain a valid output for every input of a given station.
1. `yarn test`
None
Resolves #95
=> Fix generateTributaryMaps

.env.template, .travis.yml, docs/INSTALL.md, package.json, services/kafka/start.sh, services/kafka/stop.sh, src/classes/Countertop.js, src/classes/CountertopStation.js, src/classes/CountertopWorker.js, src/classes/__test__/Countertop.unit.test.js, src/classes/__test__/CountertopStation.unit.test.js, src/classes/__test__/CountertopWorker.unit.test.js, src/tests/topology.int.test.js, src/tools/kafka/index.js
This PR adds the ability for a developer to specify kafka configuration settings when creating a Countertop.  In turn, it removes the (very simple) `kafka` tool we created and the ability to configure kafka via environment variables.
Kafka injection is now a part of the core countertop components (countertop => stations => workers)
1. `yarn test`
- `yarn install`
Resolves #99
=> Make kafka configurable via API

src/classes/Countertop.js, src/classes/CountertopStation.js, src/classes/CountertopWorker.js
This PR adds support for the `on` method in Countertop (and the various countertop components). This allows a developer to listen for appliance events (and eventually any kind of countertop event).
1. `yarn test`
- `yarn install`
Resolves #100 
Related to #82 
Relies on PR #102
=> Enable subscriptions

package.json, src/classes/CountertopWorker.js, yarn.lock
This PR updates the countertop to use AvroPayload serialization, which is much more efficient than the default serialization of `Payload`
1. `yarn test`
- `yarn install`
Resolves #104
=> Use Avro payload

src/tools/loggers/consoleLogger.js
This PR changes the default logger to use `console.debug` instead of `console.trace` for trace level logging.  It turns out console.trace posts a full stack trace which is not expected behavior of our logger.
1. `yarn test`
None
Related to #101
=> Stop using console.trace

src/classes/Countertop.js, src/classes/CountertopWorker.js, src/tools/loggers/__test__/silentLogger.unit.test.js, src/tools/loggers/index.js, src/tools/loggers/silentLogger.js
This PR replaces the default logger to be a silent logger.  This means that developers who want logs will have to pass their own logger to the countertop upon creation.
1. `yarn test`
None
Resolves #101
=> Silent default logger

CHANGELOG.md, src/classes/CountertopWorker.js
This PR fixes CountertopWorker so that it will not write to Kafka until the previous payload has been processed. 
1. `yarn test`
None
Resolves #110
=> Fix message ordering

CHANGELOG.md, src/classes/Countertop.js
This PR adds a default value for the `kafkaSettings.brokers` configuration required by KafkaJS.
1. `yarn test`
Resolves #113
=> Add a default Kafka broker

CHANGELOG.md, package.json, yarn.lock
This PR updates the version of @tvkitchen/base-classes to 1.4.0-alpha.2
Resolves #125
=> Update @tvkitchen/base-classes to 1.4.0-alpha.2

CHANGELOG.md, src/classes/CountertopWorker.js
This PR changes the retention time in Kafka to 30 seconds from 7 days.  This should mean that TV Kitchen won't fill up hard drives simply by running.
Resolves #133
=> Set Kafka retention to 30 seconds

CHANGELOG.md, src/classes/CountertopWorker.js
This PR fixes a bug where topologies with appliances that only had a subset of inputs provided would error.
Resolves #149
=> Allow partial input topologies

CHANGELOG.md, package.json, yarn.lock
This PR updates `@tvkitchen/base-interfaces` to version `4.0.0-alpha.5`.
(This fixes a bug related to transform streams in more recent versions of node)
=> Update base-interfaces to 4.0.0-alpha.5

src/index.ts, src/types/DataType.ts, src/types/LogLevel.ts, src/types/index.ts
This PR imports the base-constants values from the [@tvkitchen/base-constants](https://github.com/tvkitchen/base/tree/main/packages/constants) package and rewrites them as TypeScript.
Related to #154
=> Import base-constants

CHANGELOG.md, package.json, src/classes/Payload.ts, src/classes/__test__/Payload.unit.test.ts, src/errors/ValidationError.ts, src/errors/index.ts, src/index.ts, src/tools/ajv.ts, src/types/PayloadParameters.ts, src/types/__test__/PayloadParameters.unit.test.ts, yarn.lock
This PR incorporates [Ajv](https://www.npmjs.com/package/ajv) into the Countertop in order to support more robust runtime validation.
This is particularly important because we are serializing / deserializing between json, and ajv is quite fast at that validation.  (Note that we will probably want to use Ajv to serialize and deserialize Payloads too instead of JSON.stringify, since it is in theory 10x faster)
In addition to incorporating Ajv this fixes a few bugs I found in the tests.
Resolves #166
=> Use Ajv for validation

CHANGELOG.md, src/classes/CountertopStream.js, src/classes/CountertopTopology.js, src/classes/__tests__/CountertopTopology.unit.test.js, src/classes/__tests__/__snapshots__/CountertopTopology.unit.test.js.snap, src/tools/utils/countertop.js
This PR fixes an issue where topologies might contain duplicate stations with partially overlapping input streams. 
Resolves #159
=> Prune obsolete streams
